name: Render and Deploy Bookdown

on:
  push:
    branches:
      - master
      - main

jobs:
  build-bookdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Dependencies and render Book
        run: |
          R -e 'install.packages(c("bookdown"))'
          R -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
          R -e 'bookdown::render_book("index.Rmd")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
