name: Render and Deploy Bookdown

on:
  push:
    branches:
      - master
      - main

jobs:
  build-bookdown:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up R
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1'

      # Step 3: Restore renv library cache
      - name: Restore renv library cache
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}-renv-library
          restore-keys: |
            ${{ runner.os }}-r-

      # Step 4: Install renv and restore dependencies
      - name: Install renv and restore dependencies
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      # Step 5: Cache the renv library
      - name: Cache renv library
        uses: actions/cache@v3
        with:
          path: renv/library
          key: ${{ runner.os }}-r-${{ hashFiles('renv.lock') }}-renv-library

      # Step 6: Render Bookdown
      - name: Render Bookdown
        run: |
          R -e 'bookdown::render_book("index.Rmd")'

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
